-- DROP DATABASE IF NOT EXISTS workspacelocations;
-- CREATE DATABASE IF NOT EXISTS workspacelocations;
\c workspacelocations;
CREATE EXTENSION IF NOT EXISTS CUBE;
CREATE EXTENSION IF NOT EXISTS EARTHDISTANCE;