#!/bin/bash

###################################################
# Bash script to create database and seed
###################################################

# Path to directory bash script is living
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# if parameter 1 is not passed as argument default records to be generated to 10 million rows for 2 tables
LINES=${1:-10000000}

psql -d postgres -f createDb.sql

node models.js

# seed database
node pgSeeder.js --lines=$LINES

# remove files generated by seed because they have already been copied into the database
node removeDataFiles.js

# add in primary keys, foreign keys and indexes
node rawQueries.js
