#!/bin/bash

###################################################
# Bash script to create database and seed
###################################################

# Path to directory bash script is living
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# if parameter 1 is not passed as argument default records to be generated to 10 million rows for 2 tables
LINES=${1:-10000000}
INIT="init"

# create database
# psql -d postgres -f createDb.sql

# add necessary extensions for database
# psql -d postgres -d workspacelocations -f addExtensions.sql

# seed database
node pgSeeder.js --lines=$LINES

# remove files generated by seed because they have already been copied into the database
node removeDataFiles.js

# add in primary keys, foreign keys
node rawQueries.js

# index database
node relationship.js --init=$INIT
